var fs = require('fs')

fs.mkdirSync('./dev')
fs.mkdirSync('./dev/src')
fs.mkdirSync('./dev/src/css')
fs.mkdirSync('./dev/src/sass')
fs.mkdirSync('./dev/src/js')
fs.mkdirSync('./dev/src/images')
fs.mkdirSync('./dev/vendor')
fs.mkdirSync('./dev/vendor/css')
fs.mkdirSync('./dev/vendor/js')
fs.mkdirSync('./dev/views')
fs.mkdirSync('./dev/components')
fs.mkdirSync('./dev/components/include')
